name: DevBlog CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Prepare deployment bundle files
      run: |
        mkdir -p deploy_bundle/scripts
        cp appspec.yml deploy_bundle/
        cp -r scripts/* deploy_bundle/scripts/
        cp build/libs/be-0.0.1-SNAPSHOT.jar deploy_bundle/
        ls -l deploy_bundle
        ls -l deploy_bundle/scripts
      shell: bash
      
    - name: Make zip file
      run: |
        cd deploy_bundle
        zip -r ../devblog-deploy.zip .
      shell: bash
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: devblog-deploy
        path: ./devblog-deploy.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: devblog-deploy
    
    - name: Unzip
      run: unzip -o ./devblog-deploy.zip
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./devblog-deploy.zip s3://myawsdev-devaws-bucket/

    - name: Deploy to EC2 with CodeDeploy
      run: aws deploy create-deployment --application-name devblog-codedeploy-app --deployment-group-name devblog-deployment-group --s3-location bucket=myawsdev-devaws-bucket,bundleType=zip,key=devblog-deploy.zip

