name: DevBlog CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Make zip package
        run: |
          mkdir -p deploy
          cp build/libs/*.jar deploy/
          cp appspec.yml deploy/
          cp -r scripts/ deploy/
          cd deploy && zip -r ../deploy.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp ./deploy.zip s3://myawsdev-devaws-bucket/devblog-deploy.zip

      - name: Deploy to EC2 with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name devblog-codedeploy-app \
            --deployment-group-name devblog-deployment-group \
            --s3-location bucket=myawsdev-devaws-bucket,bundleType=zip,key=devblog-deploy.zip

